filecount: main.c file2buff.c countletter.c
	gcc -o filecount main.c file2buff.c  countletter.c
main.o: main.c 
	gcc -c main.c
file2buff.o: file2buff.c  
	gcc -c file2buff.c
countletter.o: countletter.c
	gcc -c countletter.c 
