mdc: main.c file2buff.c master_array.c fourbitcomp.c fourbitdecomp.c buff2file.c
	gcc -o mdc main.c file2buff.c  master_array.c fourbitcomp.c fourbitdecomp.c buff2file.c
#main.o: main.c 
#	gcc -c main.c
#file2buff.o: file2buff.c  
#	gcc -c file2buff.c
